export const moduleData = [
  {
    module_code: "mod-01",
    description: "Navigation",
    rank: 1,
    is_active: 1,
  },
  {
    module_code: "mod-02",
    description: "Events",
    rank: 2,
    is_active: 1,
  },
  {
    module_code: "mod-03",
    description: "Management",
    rank: 3,
    is_active: 1,
  },
  {
    module_code: "mod-04",
    description: "Settings",
    rank: 4,
    is_active: 1,
  },
];
export const submoduleData = [
  {
    module_code: "mod-01",
    submodule_code: "smod-01",
    description: "Dashboard",
    rank: 1,
    is_active: 1,
  },
  {
    module_code: "mod-02",
    submodule_code: "smod-02",
    description: "Bookings",
    rank: 2,
    is_active: 1,
  },
  {
    module_code: "mod-02",
    submodule_code: "smod-03",
    description: "Calendar - Reservations",
    rank: 3,
    is_active: 1,
  },
  {
    module_code: "mod-02",
    submodule_code: "smod-04",
    description: "Calendar - Overdues",
    rank: 4,
    is_active: 1,
  },
  {
    module_code: "mod-04",
    submodule_code: "smod-05",
    description: "Roles",
    rank: 5,
    is_active: 1,
  },
  {
    module_code: "mod-04",
    submodule_code: "smod-06",
    description: "Accounts",
    rank: 6,
    is_active: 1,
  },
  {
    module_code: "mod-04",
    submodule_code: "smod-07",
    description: "Activity Logs",
    rank: 7,
    is_active: 1,
  },
];
export const itemData = [
  {
    module_code: "mod-01",
    submodule_code: "smod-01",
    item_code: "itm-01",
    description: "View",
    rank: 1,
    is_active: 1,
  },
  {
    module_code: "mod-02",
    submodule_code: "smod-02",
    item_code: "itm-02",
    description: "List",
    rank: 2,
    is_active: 1,
  },
  {
    module_code: "mod-02",
    submodule_code: "smod-03",
    item_code: "itm-03",
    description: "View",
    rank: 3,
    is_active: 1,
  },
  {
    module_code: "mod-02",
    submodule_code: "smod-04",
    item_code: "itm-04",
    description: "List",
    rank: 4,
    is_active: 1,
  },
  {
    module_code: "mod-04",
    submodule_code: "smod-05",
    item_code: "itm-05",
    description: "View",
    rank: 5,
    is_active: 1,
  },
  {
    module_code: "mod-04",
    submodule_code: "smod-06",
    item_code: "itm-06",
    description: "View",
    rank: 6,
    is_active: 1,
  },
  {
    module_code: "mod-04",
    submodule_code: "smod-07",
    item_code: "itm-07",
    description: "View",
    rank: 7,
    is_active: 1,
  },
];
export const matrixData = [
  { role_code: "admin", item_code: "itm-01", is_active: 1 },
  { role_code: "admin", item_code: "itm-02", is_active: 1 },
  { role_code: "admin", item_code: "itm-03", is_active: 1 },
  { role_code: "admin", item_code: "itm-04", is_active: 1 },
  { role_code: "admin", item_code: "itm-05", is_active: 1 },
  { role_code: "admin", item_code: "itm-06", is_active: 1 },
  { role_code: "admin", item_code: "itm-07", is_active: 1 },
  {
    role_code: "merchant_manager",
    item_code: "itm-01",
    is_active: 1,
  },
  {
    role_code: "merchant_manager",
    item_code: "itm-02",
    is_active: 1,
  },
  {
    role_code: "merchant_manager",
    item_code: "itm-03",
    is_active: 1,
  },
  {
    role_code: "merchant_manager",
    item_code: "itm-04",
    is_active: 1,
  },
  {
    role_code: "merchant_manager",
    item_code: "itm-05",
    is_active: 1,
  },
  {
    role_code: "merchant_manager",
    item_code: "itm-06",
    is_active: 1,
  },
  {
    role_code: "merchant_manager",
    item_code: "itm-07",
    is_active: 1,
  },
  { role_code: "user", item_code: "itm-01", is_active: 1 },
  { role_code: "user", item_code: "itm-02", is_active: 1 },
  { role_code: "user", item_code: "itm-02", is_active: 1 },
  { role_code: "user", item_code: "itm-03", is_active: 1 },
  { role_code: "user", item_code: "itm-04", is_active: 1 },
  { role_code: "user", item_code: "itm-05", is_active: 1 },
  { role_code: "user", item_code: "itm-06", is_active: 1 },
  { role_code: "user", item_code: "itm-07", is_active: 1 },
];
